name       : python-wrapt
version    : 1.14.1
release    : 14
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/refs/tags/1.14.1.tar.gz : 866211ed43c2639a2452cd017bd38589e83687b1d843817c96b99d2d9d32e8d7
homepage   : https://github.com/GrahamDumpleton/wrapt
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching
description: |
    The aim of the wrapt module is to provide a transparent object proxy for Python, which can be used as the basis for the construction of function wrappers and decorator functions.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
