name       : python-wrapt
version    : 1.10.11
release    : 2
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/1.10.11.tar.gz : 948bb6ed9a633034924420de701bb0f5f95970f195a509cee2df92f752ab9ae9
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching.
description: |
    A Python module for decorators, wrappers and monkey patching.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
