name       : python-wrapt
version    : 1.13.3
release    : 11
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/refs/tags/1.13.3.tar.gz : 169a9d4af2df4fa8cd3e5f1d860089c38f4d83f10990bd1089eb2cd56ba4e3ce
homepage   : https://github.com/GrahamDumpleton/wrapt
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching
description: |
    The aim of the wrapt module is to provide a transparent object proxy for Python, which can be used as the basis for the construction of function wrappers and decorator functions.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
