name       : python-wrapt
version    : 1.12.1
release    : 8
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/1.12.1.tar.gz : 19f2043e05b76ce9b68971b387bfd8eed50c2ee1c9c0bd230edc422fec753917
homepage   : https://github.com/GrahamDumpleton/wrapt
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching
description: |
    The aim of the wrapt module is to provide a transparent object proxy for Python, which can be used as the basis for the construction of function wrappers and decorator functions.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3
