name       : python-wrapt
version    : 1.13.1
release    : 10
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/refs/tags/1.13.1.tar.gz : 6e68f02c4846ec2879834bde2cb773860cacaf04345b5188704a6240d39eb671
homepage   : https://github.com/GrahamDumpleton/wrapt
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching
description: |
    The aim of the wrapt module is to provide a transparent object proxy for Python, which can be used as the basis for the construction of function wrappers and decorator functions.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
