name       : python-wrapt
version    : 1.11.1
release    : 4
source     :
    - https://github.com/GrahamDumpleton/wrapt/archive/1.11.1.tar.gz : 8a6fb40e8f8b6a66b4ba81a4044c68e6a7b1782f21cfabc06fb765332b4c3e51
license    : BSD-2-Clause
component  : programming.python
summary    : A Python module for decorators, wrappers and monkey patching
description: |
    A Python module for decorators, wrappers and monkey patching.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
